jobs:
- job: 'BuildCommonNpmPackages'
  displayName: 'Build Common Npm Packages'
  steps:
  - checkout: self
    clean: true

  - task: NodeTool@0
    displayName: Use node 10
    inputs:
      versionSpec: "10.x"

  - script: npm i -g npm@6.14.12 --force
    displayName: Use npm version 6.14.12

  # Build typescript in ./Test and ./Test/lib
  - bash: |
        npm install
        ./node_modules/typescript/bin/tsc -p ./Tests
    displayName: Build tests lib

  # npm install
  - script: |
        npm run build
    displayName: Build Common Npm packages

  - script: |
        npm run test
    displayName: Test Common Npm packages

  # For CI runs on master, automatically publish packages
  - bash: |
        npm run publish
    condition: and(succeeded(), in(variables['build.reason'], 'IndividualCI', 'BatchedCI', 'Manual'), eq(variables['Agent.OS'], 'Windows_NT'))
    env:
      NPM_TOKEN: $(npm-automation.token)
    displayName: Publish packages (Only Windows)
    enabled: true